import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { getAnomalies } from '@/services/api';
import { useMlSection } from './useMlSection';
import { Card, EmptyNote, ErrorNote, Loading, Provenance, StatusBadge } from './parts';
import { fmtInt, fmtMoneyShort, fmtPct } from './format';
export function AnomalySection({ filters }) {
    const section = useMlSection((f) => getAnomalies(f), filters);
    const { status, data, error, appliedFilters, stale } = section;
    const inf = data?.inference;
    return (_jsxs(Card, { testId: "anomalies", title: "Anomaly Detection", subtitle: data
            ? `${data.model} · ${data.algorithm ?? ''} — daily orders/revenue outliers via IsolationForest`
            : 'Unusual trading days detected by an IsolationForest over daily orders and revenue', badge: _jsx(StatusBadge, { tone: inf ? 'ok' : 'neutral', children: data?.status ?? 'inference' }), children: [status === 'loading' && !data && _jsx(Loading, { label: "Running anomaly model\u2026" }), status === 'error' && error && _jsx(ErrorNote, { message: error, testId: "anomalies-error" }), data && inf && (_jsxs("div", { "data-testid": "anomalies-result", children: [_jsxs("div", { className: "flex flex-wrap gap-x-6 gap-y-1 text-sm text-neutral-300 my-2", children: [_jsxs("span", { children: ["Days evaluated: ", _jsx("span", { className: "text-neutral-400", children: fmtInt(inf.n_days) }), ' ', _jsxs("span", { className: "text-neutral-600 text-xs", children: ["(", inf.evaluated_from, " \u2192 ", inf.evaluated_to, ")"] })] }), _jsxs("span", { children: ["Anomalies: ", _jsx("span", { className: "text-neutral-400", children: fmtInt(inf.n_anomalies) })] }), _jsxs("span", { children: ["Share: ", _jsx("span", { className: "text-neutral-400", children: fmtPct(inf.anomaly_share) })] }), _jsxs("span", { children: ["Contamination (training):", ' ', _jsx("span", { className: "text-neutral-400", children: inf.contamination != null ? inf.contamination.toFixed(2) : 'n/a' })] })] }), inf.n_days === 0 ? (_jsx(EmptyNote, { message: "No days in the selected date range.", testId: "anomalies-empty" })) : inf.top_anomalies.length === 0 ? (_jsx(EmptyNote, { message: "No anomalies detected for the selected period.", testId: "anomalies-empty" })) : (_jsxs("table", { className: "w-full text-sm mt-1", "data-testid": "anomalies-table", children: [_jsxs("caption", { className: "text-left text-[11px] text-neutral-600 pb-1", children: ["Showing up to ", inf.top_anomalies.length, " most anomalous days (score ascending)."] }), _jsx("thead", { children: _jsxs("tr", { className: "text-left text-xs text-neutral-500 border-b border-neutral-800", children: [_jsx("th", { className: "py-1.5 pr-2", children: "Date" }), _jsx("th", { className: "py-1.5 pr-2", children: "Orders" }), _jsx("th", { className: "py-1.5 pr-2", children: "Revenue" }), _jsx("th", { className: "py-1.5", children: "Anomaly score" })] }) }), _jsx("tbody", { children: inf.top_anomalies.map((a) => (_jsxs("tr", { className: "border-b border-neutral-800/60", "data-testid": "anomaly-row", children: [_jsx("td", { className: "py-1.5 pr-2 font-medium", children: a.date.slice(0, 10) }), _jsx("td", { className: "py-1.5 pr-2", children: fmtInt(a.orders) }), _jsx("td", { className: "py-1.5 pr-2", children: fmtMoneyShort(a.revenue) }), _jsx("td", { className: "py-1.5 text-amber-300", children: a.score.toFixed(4) })] }, a.date))) })] })), _jsx("p", { className: "text-[11px] text-neutral-600 mt-2", children: inf.score_definition }), _jsx(Provenance, { filters: appliedFilters, stale: stale, generatedAt: data.metadata.generated_at ?? null, extra: `status: ${data.status}` })] }))] }));
}
