import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { getMlAdminStatus } from '@/services/api';
export default function AdminMl() {
    const [ml, setMl] = useState(null);
    const [error, setError] = useState(null);
    useEffect(() => {
        getMlAdminStatus()
            .then(setMl)
            .catch(() => setError('Could not load ML administration status.'));
    }, []);
    if (error)
        return _jsx("div", { className: "text-red-400 text-sm", children: error });
    if (!ml)
        return _jsx("div", { className: "text-neutral-400 text-sm", children: "Loading ML status\u2026" });
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "bg-neutral-900/60 border border-neutral-800 rounded-lg p-4", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("h2", { className: "font-medium", children: "Model artifacts" }), _jsxs("span", { className: "text-xs text-neutral-500", children: [ml.artifact_count, " deployed"] })] }), _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-4 text-sm mb-4", children: [_jsxs("div", { children: [_jsx("div", { className: "text-neutral-500 text-xs uppercase", children: "Metadata entries" }), ml.metadata_entries] }), _jsxs("div", { children: [_jsx("div", { className: "text-neutral-500 text-xs uppercase", children: "Training data" }), ml.data_dir_exists ? 'present' : 'missing'] }), _jsxs("div", { className: "col-span-2", children: [_jsx("div", { className: "text-neutral-500 text-xs uppercase", children: "Retraining" }), ml.retraining] })] }), ml.artifacts.length > 0 ? (_jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { className: "text-neutral-500 text-xs uppercase", children: _jsxs("tr", { children: [_jsx("th", { className: "text-left py-1", children: "Artifact" }), _jsx("th", { className: "text-right py-1", children: "Size" }), _jsx("th", { className: "text-right py-1", children: "Last modified" })] }) }), _jsx("tbody", { children: ml.artifacts.map((a) => (_jsxs("tr", { className: "border-t border-neutral-800", children: [_jsx("td", { className: "py-1", children: a.file }), _jsxs("td", { className: "py-1 text-right", children: [(a.size_bytes / 1024).toFixed(1), " kB"] }), _jsx("td", { className: "py-1 text-right", children: a.modified_at.slice(0, 19).replace('T', ' ') })] }, a.file))) })] })) : (_jsx("div", { className: "text-sm text-neutral-500", children: "No trained artifacts found on disk." })), _jsx("div", { className: "text-xs text-neutral-500 mt-3", children: ml.models_dir })] }), _jsxs("div", { className: "bg-neutral-900/60 border border-neutral-800 rounded-lg p-4", children: [_jsx("h2", { className: "font-medium mb-3", children: "Deployment status" }), _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { className: "text-neutral-500 text-xs uppercase", children: _jsxs("tr", { children: [_jsx("th", { className: "text-left py-1", children: "Feature" }), _jsx("th", { className: "text-left py-1", children: "Status" }), _jsx("th", { className: "text-left py-1", children: "Models" })] }) }), _jsx("tbody", { children: ml.features.map((f) => (_jsxs("tr", { className: "border-t border-neutral-800", children: [_jsx("td", { className: "py-1", children: f.name }), _jsx("td", { className: "py-1", children: f.status }), _jsx("td", { className: "py-1 text-neutral-500", children: f.models.map((m) => `${m.algorithm ?? '—'}${m.artifact_available ? '' : ' (no artifact)'}`).join(', ') || '—' })] }, f.name))) })] })] })] }));
}
